export const routes = {
    WELCOMESCREEN: 'WelcomeScreen',
    START: 'Start',
    MYSCREEN: 'MyScreen',
    CHATMANAGER: 'ChatManager',
    CHATSCREEN: 'ChatScreen',
    HOMESCREEN: 'HomeScreen',
    ADS: 'Ads',
    APP: 'App',
    PAYMENT_PROCESSING: 'PaymentProcessing',
    ADMOB: 'Admob',
    SETTINGS: 'Settings',
    FIRSTSCREEN: 'FirstScreen',
    ADSCREEN: 'AdScreen',
    SEARCHLIST: 'SearchList',
    COUNTRYCHAT: 'CountryChat',
    CHATROOM: 'ChatRoom',
    COMMONLIKES: 'CommonLikes',
    ACCOUNTHEALTH: 'AccountHealth',
};